# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

freq3 <- function(x, groupEnd, id) {
    .Call('_CVAA_freq3', PACKAGE = 'CVAA', x, groupEnd, id)
}

